# Generated by Django 5.2.1 on 2025-09-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='name',
            field=models.CharField(max_length=41),
        ),
    ]
