# Generated by Django 5.2.1 on 2025-09-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_lista_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
